### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [erniejamison/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by erniejamison** [comment]
I've added the responsive meta tag to the head of application.html.erb in order to allow the browsers of smaller devices such as phones to render the width of the page at the width if the devices screen.

`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by BillyMassey** [comment]
Good Job!
